#!/bin/bash
install_monitor() {

    install() {
        SOURCES="/etc/apt/sources.list.d/$SOURCES"

        log "Defining the apt lookup at $SOURCES"
        echo "deb $REPO" > "$SOURCES"

        log "Register the GPG key for the new lookup"  
        curl -sL "$KEY" | apt-key add - >&3

        log "Update the local package list."
        apt-get update >&3

        log "Install the tool $TOOL"
        apt-get install -y --force-yes "$TOOL" >&3
    }

    debInst() {
        dpkg-query -Wf'${db:Status-abbrev}' "$1" 2>/dev/null | grep -q '^i'
    }

    step "Installing newrelic"
        REPO="http://apt.newrelic.com/debian/ newrelic non-free" \
        SOURCES="newrelic.list" \
        KEY="https://download.newrelic.com/548C16BF.gpg" \
        TOOL="newrelic-sysmond" \
            install
    end

    step "Installing td_agent"
        log "Preparing log folder $LOG_FOLDER for user td-agent"
        LOG_FOLDER="/var/log/td-agent"

        log "Creating the folder"
        mkdir -p $LOG_FOLDER

        log "Setting a user"
        chown -R td-agent $LOG_FOLDER || true

        VERSION="lucid"
        if available "lsb_release"; then
            VERSION="$(lsb_release -c -s)"
        fi

        if [[ "$VERSION" != "precise" ]]; then
            if ! debInst "libssl0.9.8" ; then
                TMPLIB="/tmp/libssl098"
                curl -s http://snapshot.debian.org/archive/debian/20110406T213352Z/pool/main/o/openssl098/libssl0.9.8_0.9.8o-7_i386.deb > $TMPLIB
                dpkg i "$TMPLIB"
            fi
            SYSTEM="debian"
        else
            SYSTEM="precise"
        fi

        REPO="http://packages.treasuredata.com/$SYSTEM/ $VERSION contrib" \
        SOURCES="treasure-data.list" \
        KEY="http://packages.treasuredata.com/GPG-KEY-td-agent" \
        TOOL="td-agent" \
            install
    end
}
