#!/bin/bash

install_monitor() {
    step "Installing newrelic service"
        log "Download the newrelic rpm package"
        rpm -Uvh --force http://download.newrelic.com/pub/newrelic/el5/i386/newrelic-repo-5-3.noarch.rpm >&3

        log "Install the newrelic service"
        yum install -y newrelic-sysmond >&3
    end

    step "Installing td_agent"
        curl -sL http://toolbelt.treasuredata.com/sh/install-redhat.sh | sh >&3
    end
}