#!/bin/bash

install_monitor() {
    step "Installing newrelic"

        SOURCES="/etc/apt/sources.list.d/newrelic.list"
        REPO="http://apt.newrelic.com/debian/"

        if [[ "$( cat $SOURCES | grep $REPO )" == "" ]]; then
            log "Adding newrelic apt lookup"
            echo deb $REPO newrelic non-free >> $SOURCES >&3
            
            log "Trust the New Relic GPG key."  
            curl -sL https://download.newrelic.com/548C16BF.gpg | apt-key add - >&3
        fi
        
        log "Update the local package list."
        apt-get update >&3

        log "Install the Server Monitor package"
        log "Run the install command:"
        apt-get install newrelic-sysmond >&3
    end

    step "Installing td_agent"
        curl -sL http://toolbelt.treasuredata.com/sh/install-ubuntu-precise.sh | sh >&3
    end
}