#!/bin/bash

install_monitor() {

    install() {
        SOURCES="/etc/apt/sources.list.d/$SOURCES"

        log "Defining the apt lookup at $SOURCES"
        echo $REPO > "$SOURCES"

        log "Register the GPG key for the new lookup"  
        curl -sL $KEY | apt-key add - >&3

        log "Update the local package list."
        apt-get update >&3

        log "Install the tool $TOOL"
        apt-get install "$TOOL" >&3
    }

    step "Installing newrelic"
        REPO="deb http://apt.newrelic.com/debian/ newrelic non-free" \
        SOURCES="/etc/apt/sources.list.d/newrelic.list" \
        KEY="https://download.newrelic.com/548C16BF.gpg" \
        TOOL="newrelic-sysmond" \
            install
    end

    step "Installing td_agent"

        REPO="deb http://packages.treasuredata.com/precise/ precise contrib" \
        SOURCES="treasure-data.list" \
        KEY="https://download.newrelic.com/548C16BF.gpg" \
        TOOL="newrelic-sysmond" \
            install
        echo "" > 

        curl -sL http://packages.treasuredata.com/GPG-KEY-td-agent | apt-key add - >&3

        # update your sources
        apt-get update

        # install the toolbelt
        apt-get install -y --force-yes td-agent
    end
}