#!/bin/bash

function install_monitor {
    block "Installing newrelic"
        log "Adding newrelic apt lookup"
        echo deb http://apt.newrelic.com/debian/ newrelic non-free >> /etc/apt/sources.list.d/newrelic.list
        
        log "Trust the New Relic GPG key."
        wget -O- https://download.newrelic.com/548C16BF.gpg | apt-key add -
        
        log "Update the local package list."
        apt-get update

        log "Install the Server Monitor package"
        log "Run the install command:"
        apt-get install newrelic-sysmond
    end

    block "Installing td_agent"
        curl -L http://toolbelt.treasuredata.com/sh/install-ubuntu-precise.sh | sh
    end
}